cache: pip
language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 2.7
    - python: nightly
    - python: pypy
    - python: pypy3

install:
  - pip install . pytest coverage codecov flake8 isort
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - flake8 prompt_toolkit
  - coverage run -m pytest

  # Check wheather the imports were sorted correctly.
  # When this fails, please run ./tools/sort-imports.sh
  - isort -c -m 3 -tc -rc prompt_toolkit

after_success:
  - codecov
