os: linux
dist: focal
cache: pip
language: python

jobs:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6

install:
  - pip install . black coverage codecov flake8 isort mypy pytest
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - flake8 .
  - coverage run -m pytest

  # Run type checker.
  - mypy prompt_toolkit

  # Check wheather the imports were sorted correctly.
  # When this fails, please run ./tools/sort-imports.sh
  - isort -c -rc --profile black prompt_toolkit examples tests setup.py

  - black --check prompt_toolkit examples tests setup.py

after_success:
  - codecov
